use strict;
use warnings;
use Test::More;

# TODO: Add tests for code generated by protoc-gen-perl-pb
ok(1, 'Placeholder test');

{
    local $TODO = 'Engineering Excellence features not yet implemented';
    ok(0, "Test precomputed field name hashes");
    ok(0, "Test embedded source code info");
    ok(0, "Test generated Type::Tiny constraints");
}

done_testing();
