/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.51 from the
 * contents of Protobuf.xs. Do not edit this file, edit Protobuf.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Protobuf.xs"
#define PERL_NO_GET_CONTEXT
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#include "ppport.h"

#include "xs/protobuf/arena.h"
#include "xs/protobuf/message.h"
#include "xs/message/message.h"
#include "xs/message/access.h"
#include "xs/message/serialize.h"
#include "xs/descriptor_pool/pool.h"
#include "xs/descriptor_pool/add.h"
#include "xs/descriptor_pool/find.h"
#include "xs/descriptor/file.h"
#include "xs/descriptor/message.h"
#include "xs/descriptor/enum.h"
#include "xs/descriptor/field.h"

#line 30 "Protobuf.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
	    Perl_croak_nocontext("Usage: %s::%s(%s)", hvname, gvname, params);
        else
	    Perl_croak_nocontext("Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
	Perl_croak_nocontext("Usage: CODE(0x%" UVxf ")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#define croak_xs_usage        S_croak_xs_usage

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#if PERL_VERSION_LE(5, 21, 5)
#  define newXS_deffile(a,b) Perl_newXS(aTHX_ a,b,file)
#else
#  define newXS_deffile(a,b) Perl_newXS_deffile(aTHX_ a,b)
#endif

#line 174 "Protobuf.c"

XS_EUPXS(XS_Protobuf__Arena__xs_create_raw); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__Arena__xs_create_raw)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	IV	RETVAL;
	dXSTARG;
#line 28 "Protobuf.xs"
        RETVAL = PTR2IV(PerlUpb_Arena_CreateRaw(aTHX));
#line 187 "Protobuf.c"
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Protobuf__Arena__xs_destroy_raw); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__Arena__xs_destroy_raw)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "ptr_iv");
    {
	IV	ptr_iv = (IV)SvIV(ST(0))
;
#line 36 "Protobuf.xs"
        PerlUpb_Arena_DestroyRaw(aTHX_ INT2PTR(void*, ptr_iv));
#line 206 "Protobuf.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Protobuf__DescriptorPool__xs_create_raw); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__DescriptorPool__xs_create_raw)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	IV	RETVAL;
	dXSTARG;
#line 44 "Protobuf.xs"
        RETVAL = PTR2IV(PerlUpb_DescriptorPool_CreateRaw(aTHX));
#line 223 "Protobuf.c"
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Protobuf__DescriptorPool__xs_destroy_raw); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__DescriptorPool__xs_destroy_raw)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "ptr_iv");
    {
	IV	ptr_iv = (IV)SvIV(ST(0))
;
#line 52 "Protobuf.xs"
        PerlUpb_DescriptorPool_DestroyRaw(aTHX_ INT2PTR(void*, ptr_iv));
#line 242 "Protobuf.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Protobuf__DescriptorPool__xs_generated_pool); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__DescriptorPool__xs_generated_pool)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	SV *	RETVAL;
#line 57 "Protobuf.xs"
        RETVAL = PerlUpb_DescriptorPool_GeneratedPool(aTHX);
#line 258 "Protobuf.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Protobuf__DescriptorPool__xs_add_serialized_file); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__DescriptorPool__xs_add_serialized_file)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, serialized");
    {
	SV*	self = ST(0)
;
	SV*	serialized = ST(1)
;
	SV *	RETVAL;
#line 66 "Protobuf.xs"
        RETVAL = PerlUpb_DescriptorPool_AddSerializedFile(aTHX_ self, serialized);
#line 280 "Protobuf.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Protobuf__DescriptorPool__xs_add_serialized_file_descriptor_set); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__DescriptorPool__xs_add_serialized_file_descriptor_set)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, serialized");
    {
	SV*	self = ST(0)
;
	SV*	serialized = ST(1)
;
	SV *	RETVAL;
#line 75 "Protobuf.xs"
        RETVAL = PerlUpb_DescriptorPool_AddSerializedFileDescriptorSet(aTHX_ self, serialized);
#line 302 "Protobuf.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Protobuf__DescriptorPool__xs_find_file_by_name); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__DescriptorPool__xs_find_file_by_name)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, name");
    {
	SV*	self = ST(0)
;
	const char*	name = (const char *)SvPV_nolen(ST(1))
;
	SV *	RETVAL;
#line 84 "Protobuf.xs"
        RETVAL = PerlUpb_DescriptorPool_FindFileByName(aTHX_ self, name);
#line 324 "Protobuf.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Protobuf__DescriptorPool__xs_find_message_by_name); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__DescriptorPool__xs_find_message_by_name)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, name");
    {
	SV*	self = ST(0)
;
	const char*	name = (const char *)SvPV_nolen(ST(1))
;
	SV *	RETVAL;
#line 93 "Protobuf.xs"
        RETVAL = PerlUpb_DescriptorPool_FindMessageByName(aTHX_ self, name);
#line 346 "Protobuf.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Protobuf__DescriptorPool__xs_find_enum_by_name); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__DescriptorPool__xs_find_enum_by_name)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, name");
    {
	SV*	self = ST(0)
;
	const char*	name = (const char *)SvPV_nolen(ST(1))
;
	SV *	RETVAL;
#line 102 "Protobuf.xs"
        RETVAL = PerlUpb_DescriptorPool_FindEnumByName(aTHX_ self, name);
#line 368 "Protobuf.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Protobuf__DescriptorPool__xs_find_extension_by_name); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__DescriptorPool__xs_find_extension_by_name)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, name");
    {
	SV*	self = ST(0)
;
	const char*	name = (const char *)SvPV_nolen(ST(1))
;
	SV *	RETVAL;
#line 111 "Protobuf.xs"
        RETVAL = PerlUpb_DescriptorPool_FindExtensionByName(aTHX_ self, name);
#line 390 "Protobuf.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Protobuf__Descriptor__File__xs_name); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__Descriptor__File__xs_name)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	SV*	self = ST(0)
;
	const char *	RETVAL;
	dXSTARG;
#line 122 "Protobuf.xs"
        const upb_FileDef* file = PerlUpb_FileDef_GetFile(aTHX_ self);
        RETVAL = file ? upb_FileDef_Name(file) : NULL;
#line 412 "Protobuf.c"
	sv_setpv(TARG, RETVAL);
	XSprePUSH;
	PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Protobuf__Descriptor__File__xs_package); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__Descriptor__File__xs_package)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	SV*	self = ST(0)
;
	const char *	RETVAL;
	dXSTARG;
#line 131 "Protobuf.xs"
        const upb_FileDef* file = PerlUpb_FileDef_GetFile(aTHX_ self);
        RETVAL = file ? upb_FileDef_Package(file) : NULL;
#line 435 "Protobuf.c"
	sv_setpv(TARG, RETVAL);
	XSprePUSH;
	PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Protobuf__Descriptor__File__xs_top_level_message_count); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__Descriptor__File__xs_top_level_message_count)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	SV*	self = ST(0)
;
	int	RETVAL;
	dXSTARG;
#line 140 "Protobuf.xs"
        const upb_FileDef* file = PerlUpb_FileDef_GetFile(aTHX_ self);
        RETVAL = file ? upb_FileDef_TopLevelMessageCount(file) : 0;
#line 458 "Protobuf.c"
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Protobuf__Descriptor__File__xs_top_level_message); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__Descriptor__File__xs_top_level_message)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, index");
    {
	SV*	self = ST(0)
;
	int	index = (int)SvIV(ST(1))
;
	SV *	RETVAL;
#line 150 "Protobuf.xs"
        const upb_FileDef* file = PerlUpb_FileDef_GetFile(aTHX_ self);
        if (file && index >= 0 && index < upb_FileDef_TopLevelMessageCount(file)) {
            RETVAL = PerlUpb_MessageDef_GetWrapper(aTHX_ upb_FileDef_TopLevelMessage(file, index));
        } else {
            RETVAL = &PL_sv_undef;
        }
#line 485 "Protobuf.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Protobuf__Descriptor__MessageDef__xs_full_name); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__Descriptor__MessageDef__xs_full_name)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	SV*	self = ST(0)
;
	const char *	RETVAL;
	dXSTARG;
#line 166 "Protobuf.xs"
        const upb_MessageDef* m = PerlUpb_MessageDef_GetMessage(aTHX_ self);
        RETVAL = m ? upb_MessageDef_FullName(m) : NULL;
#line 507 "Protobuf.c"
	sv_setpv(TARG, RETVAL);
	XSprePUSH;
	PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Protobuf__Descriptor__MessageDef__xs_name); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__Descriptor__MessageDef__xs_name)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	SV*	self = ST(0)
;
	const char *	RETVAL;
	dXSTARG;
#line 175 "Protobuf.xs"
        const upb_MessageDef* m = PerlUpb_MessageDef_GetMessage(aTHX_ self);
        RETVAL = m ? upb_MessageDef_Name(m) : NULL;
#line 530 "Protobuf.c"
	sv_setpv(TARG, RETVAL);
	XSprePUSH;
	PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Protobuf__Descriptor__MessageDef__xs_field_count); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__Descriptor__MessageDef__xs_field_count)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	SV*	self = ST(0)
;
	int	RETVAL;
	dXSTARG;
#line 184 "Protobuf.xs"
        const upb_MessageDef* m = PerlUpb_MessageDef_GetMessage(aTHX_ self);
        RETVAL = m ? upb_MessageDef_FieldCount(m) : 0;
#line 553 "Protobuf.c"
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Protobuf__Descriptor__MessageDef__xs_field); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__Descriptor__MessageDef__xs_field)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, index");
    {
	SV*	self = ST(0)
;
	int	index = (int)SvIV(ST(1))
;
	SV *	RETVAL;
#line 194 "Protobuf.xs"
        const upb_MessageDef* m = PerlUpb_MessageDef_GetMessage(aTHX_ self);
        if (m && index >= 0 && index < upb_MessageDef_FieldCount(m)) {
            RETVAL = PerlUpb_FieldDef_GetWrapper(aTHX_ upb_MessageDef_Field(m, index));
        } else {
            RETVAL = &PL_sv_undef;
        }
#line 580 "Protobuf.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Protobuf__Descriptor__MessageDef__xs_find_field_by_name); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__Descriptor__MessageDef__xs_find_field_by_name)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, name");
    {
	SV*	self = ST(0)
;
	SV*	name = ST(1)
;
	SV *	RETVAL;
#line 208 "Protobuf.xs"
        const upb_MessageDef* m = PerlUpb_MessageDef_GetMessage(aTHX_ self);
        STRLEN len;
        const char* name_ptr = SvPV(name, len);
        const upb_FieldDef* f = m ? PerlUpb_MessageDef_FindFieldByNameWithSize(aTHX_ m, name_ptr, len) : NULL;
        RETVAL = f ? PerlUpb_FieldDef_GetWrapper(aTHX_ f) : &PL_sv_undef;
#line 606 "Protobuf.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Protobuf__Descriptor__MessageDef__xs_find_field_by_number); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__Descriptor__MessageDef__xs_find_field_by_number)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, number");
    {
	SV*	self = ST(0)
;
	int	number = (int)SvIV(ST(1))
;
	SV *	RETVAL;
#line 221 "Protobuf.xs"
        const upb_MessageDef* m = PerlUpb_MessageDef_GetMessage(aTHX_ self);
        const upb_FieldDef* f = m ? PerlUpb_MessageDef_FindFieldByNumber(aTHX_ m, number) : NULL;
        RETVAL = f ? PerlUpb_FieldDef_GetWrapper(aTHX_ f) : &PL_sv_undef;
#line 630 "Protobuf.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Protobuf__Descriptor__Enum__xs_full_name); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__Descriptor__Enum__xs_full_name)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	SV*	self = ST(0)
;
	const char *	RETVAL;
	dXSTARG;
#line 234 "Protobuf.xs"
        const upb_EnumDef* e = PerlUpb_EnumDef_GetEnum(aTHX_ self);
        RETVAL = e ? upb_EnumDef_FullName(e) : NULL;
#line 652 "Protobuf.c"
	sv_setpv(TARG, RETVAL);
	XSprePUSH;
	PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Protobuf__Descriptor__Enum__xs_name); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__Descriptor__Enum__xs_name)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	SV*	self = ST(0)
;
	const char *	RETVAL;
	dXSTARG;
#line 243 "Protobuf.xs"
        const upb_EnumDef* e = PerlUpb_EnumDef_GetEnum(aTHX_ self);
        RETVAL = e ? upb_EnumDef_Name(e) : NULL;
#line 675 "Protobuf.c"
	sv_setpv(TARG, RETVAL);
	XSprePUSH;
	PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Protobuf__Descriptor__Enum__xs_value_count); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__Descriptor__Enum__xs_value_count)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	SV*	self = ST(0)
;
	int	RETVAL;
	dXSTARG;
#line 252 "Protobuf.xs"
        const upb_EnumDef* e = PerlUpb_EnumDef_GetEnum(aTHX_ self);
        RETVAL = e ? upb_EnumDef_ValueCount(e) : 0;
#line 698 "Protobuf.c"
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Protobuf__Descriptor__Field__xs_name); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__Descriptor__Field__xs_name)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	SV*	self = ST(0)
;
	const char *	RETVAL;
	dXSTARG;
#line 264 "Protobuf.xs"
        const upb_FieldDef* f = PerlUpb_FieldDef_GetField(aTHX_ self);
        RETVAL = f ? upb_FieldDef_Name(f) : NULL;
#line 720 "Protobuf.c"
	sv_setpv(TARG, RETVAL);
	XSprePUSH;
	PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Protobuf__Descriptor__Field__xs_full_name); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__Descriptor__Field__xs_full_name)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	SV*	self = ST(0)
;
	const char *	RETVAL;
	dXSTARG;
#line 273 "Protobuf.xs"
        const upb_FieldDef* f = PerlUpb_FieldDef_GetField(aTHX_ self);
        RETVAL = f ? upb_FieldDef_FullName(f) : NULL;
#line 743 "Protobuf.c"
	sv_setpv(TARG, RETVAL);
	XSprePUSH;
	PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Protobuf__Descriptor__Field__xs_number); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__Descriptor__Field__xs_number)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	SV*	self = ST(0)
;
	uint32_t	RETVAL;
	dXSTARG;
#line 282 "Protobuf.xs"
        const upb_FieldDef* f = PerlUpb_FieldDef_GetField(aTHX_ self);
        RETVAL = f ? upb_FieldDef_Number(f) : 0;
#line 766 "Protobuf.c"
	XSprePUSH;
	PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Protobuf__Descriptor__Field__xs_type); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__Descriptor__Field__xs_type)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	SV*	self = ST(0)
;
	int	RETVAL;
	dXSTARG;
#line 291 "Protobuf.xs"
        const upb_FieldDef* f = PerlUpb_FieldDef_GetField(aTHX_ self);
        RETVAL = f ? upb_FieldDef_Type(f) : 0;
#line 788 "Protobuf.c"
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Protobuf__Descriptor__Field__xs_label); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__Descriptor__Field__xs_label)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	SV*	self = ST(0)
;
	int	RETVAL;
	dXSTARG;
#line 300 "Protobuf.xs"
        const upb_FieldDef* f = PerlUpb_FieldDef_GetField(aTHX_ self);
        RETVAL = f ? upb_FieldDef_Label(f) : 0;
#line 810 "Protobuf.c"
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Protobuf__Descriptor__Field__xs_is_repeated); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__Descriptor__Field__xs_is_repeated)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	SV*	self = ST(0)
;
	bool	RETVAL;
#line 309 "Protobuf.xs"
        const upb_FieldDef* f = PerlUpb_FieldDef_GetField(aTHX_ self);
        RETVAL = f ? upb_FieldDef_IsRepeated(f) : false;
#line 831 "Protobuf.c"
	ST(0) = boolSV(RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Protobuf__Descriptor__Field__xs_is_map); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__Descriptor__Field__xs_is_map)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	SV*	self = ST(0)
;
	bool	RETVAL;
#line 318 "Protobuf.xs"
        const upb_FieldDef* f = PerlUpb_FieldDef_GetField(aTHX_ self);
        RETVAL = f ? upb_FieldDef_IsMap(f) : false;
#line 851 "Protobuf.c"
	ST(0) = boolSV(RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Protobuf__Descriptor__Field__xs_message_type); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__Descriptor__Field__xs_message_type)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	SV*	self = ST(0)
;
	SV *	RETVAL;
#line 327 "Protobuf.xs"
        const upb_FieldDef* f = PerlUpb_FieldDef_GetField(aTHX_ self);
        const upb_MessageDef* m = f ? upb_FieldDef_MessageSubDef(f) : NULL;
        RETVAL = m ? PerlUpb_MessageDef_GetWrapper(aTHX_ m) : &PL_sv_undef;
#line 872 "Protobuf.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Protobuf__Descriptor__Field__xs_enum_type); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__Descriptor__Field__xs_enum_type)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	SV*	self = ST(0)
;
	SV *	RETVAL;
#line 337 "Protobuf.xs"
        const upb_FieldDef* f = PerlUpb_FieldDef_GetField(aTHX_ self);
        const upb_EnumDef* e = f ? upb_FieldDef_EnumSubDef(f) : NULL;
        RETVAL = e ? PerlUpb_EnumDef_GetWrapper(aTHX_ e) : &PL_sv_undef;
#line 894 "Protobuf.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Protobuf__Message__xs_new_from_class); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__Message__xs_new_from_class)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "class_name");
    {
	const char*	class_name = (const char *)SvPV_nolen(ST(0))
;
	SV *	RETVAL;
#line 350 "Protobuf.xs"
        char* full_name = savepv(class_name);
        for (char* p = full_name; *p; p++) {
            if (*p == ':' && *(p+1) == ':') {
                *p = '.';
                memmove(p+1, p+2, strlen(p+2) + 1);
            }
        }

        SV* pool_sv = PerlUpb_DescriptorPool_GeneratedPool(aTHX);
        const upb_DefPool* pool = PerlUpb_DescriptorPool_GetPool(aTHX_ pool_sv);
        const upb_MessageDef* mdef = upb_DefPool_FindMessageByName(pool, full_name);

        if (!mdef) {
            Safefree(full_name);
            croak("Could not find descriptor for message class %s", class_name);
        }

        RETVAL = PerlUpb_Message_NewMessage(aTHX_ PerlUpb_MessageDef_GetWrapper(aTHX_ mdef));
        Safefree(full_name);
#line 932 "Protobuf.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Protobuf__Message__xs_free); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__Message__xs_free)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	SV*	self = ST(0)
;
#line 376 "Protobuf.xs"
        PerlUpb_Message_Free(aTHX_ self);
#line 951 "Protobuf.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Protobuf__Message__xs_get); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__Message__xs_get)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, field_name");
    {
	SV*	self = ST(0)
;
	const char*	field_name = (const char *)SvPV_nolen(ST(1))
;
	SV *	RETVAL;
#line 383 "Protobuf.xs"
        const upb_MessageDef* mdef = PerlUpb_Message_GetDef(aTHX_ self);
        const upb_FieldDef* fdef = PerlUpb_MessageDef_FindFieldByName(aTHX_ mdef, field_name);
        if (!fdef) {
            croak("Field '%s' not found in message '%s'", field_name, upb_MessageDef_FullName(mdef));
        }
        RETVAL = PerlUpb_Message_GetField(aTHX_ self, fdef);
#line 976 "Protobuf.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Protobuf__Message__xs_set); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__Message__xs_set)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "self, field_name, value");
    {
	SV*	self = ST(0)
;
	const char*	field_name = (const char *)SvPV_nolen(ST(1))
;
	SV*	value = ST(2)
;
#line 398 "Protobuf.xs"
        const upb_MessageDef* mdef = PerlUpb_Message_GetDef(aTHX_ self);
        const upb_FieldDef* fdef = PerlUpb_MessageDef_FindFieldByName(aTHX_ mdef, field_name);
        if (!fdef) {
            croak("Field '%s' not found in message '%s'", field_name, upb_MessageDef_FullName(mdef));
        }
        PerlUpb_Message_SetField(aTHX_ self, fdef, value);
#line 1004 "Protobuf.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Protobuf__Message__xs_serialize); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__Message__xs_serialize)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	SV*	self = ST(0)
;
	SV *	RETVAL;
#line 409 "Protobuf.xs"
        RETVAL = PerlUpb_Message_Serialize(aTHX_ self);
#line 1022 "Protobuf.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Protobuf__Message__xs_parse); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Protobuf__Message__xs_parse)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "class_name, data");
    {
	const char*	class_name = (const char *)SvPV_nolen(ST(0))
;
	SV*	data = ST(1)
;
	SV *	RETVAL;
#line 418 "Protobuf.xs"
        char* full_name = savepv(class_name);
        for (char* p = full_name; *p; p++) {
            if (*p == ':' && *(p+1) == ':') {
                *p = '.';
                memmove(p+1, p+2, strlen(p+2) + 1);
            }
        }

        SV* pool_sv = PerlUpb_DescriptorPool_GeneratedPool(aTHX);
        const upb_DefPool* pool = PerlUpb_DescriptorPool_GetPool(aTHX_ pool_sv);
        const upb_MessageDef* mdef = upb_DefPool_FindMessageByName(pool, full_name);
        Safefree(full_name);

        if (!mdef) {
            croak("Could not find descriptor for message class %s", class_name);
        }

        STRLEN len;
        const char* buf = SvPV(data, len);

        SV* arena_sv = PerlUpb_Arena_New(aTHX);
        upb_Arena* arena = PerlUpb_Arena_Get(aTHX_ arena_sv);

        const upb_MiniTable* mt = upb_MessageDef_MiniTable(mdef);
        upb_Message* msg = upb_Message_New(mt, arena);

        upb_DecodeStatus status = upb_Decode(buf, len, msg, mt, NULL, 0, arena);
        if (status != kUpb_DecodeStatus_Ok) {
            SvREFCNT_dec(arena_sv);
            croak("Failed to parse message: %d", status);
        }

        RETVAL = PerlUpb_WrapMessage(aTHX_ msg, mdef, arena_sv);
        SvREFCNT_dec(arena_sv);
#line 1077 "Protobuf.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C" {
#endif
XS_EXTERNAL(boot_Protobuf); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Protobuf)
{
#if PERL_VERSION_LE(5, 21, 5)
    dVAR; dXSARGS;
#else
    dVAR; dXSBOOTARGSXSAPIVERCHK;
#endif
#if PERL_VERSION_LE(5, 8, 999) /* PERL_VERSION_LT is 5.33+ */
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(file);

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#if PERL_VERSION_LE(5, 21, 5)
    XS_VERSION_BOOTCHECK;
#  ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#  endif
#endif

        newXS_deffile("Protobuf::Arena::_xs_create_raw", XS_Protobuf__Arena__xs_create_raw);
        newXS_deffile("Protobuf::Arena::_xs_destroy_raw", XS_Protobuf__Arena__xs_destroy_raw);
        newXS_deffile("Protobuf::DescriptorPool::_xs_create_raw", XS_Protobuf__DescriptorPool__xs_create_raw);
        newXS_deffile("Protobuf::DescriptorPool::_xs_destroy_raw", XS_Protobuf__DescriptorPool__xs_destroy_raw);
        newXS_deffile("Protobuf::DescriptorPool::_xs_generated_pool", XS_Protobuf__DescriptorPool__xs_generated_pool);
        newXS_deffile("Protobuf::DescriptorPool::_xs_add_serialized_file", XS_Protobuf__DescriptorPool__xs_add_serialized_file);
        newXS_deffile("Protobuf::DescriptorPool::_xs_add_serialized_file_descriptor_set", XS_Protobuf__DescriptorPool__xs_add_serialized_file_descriptor_set);
        newXS_deffile("Protobuf::DescriptorPool::_xs_find_file_by_name", XS_Protobuf__DescriptorPool__xs_find_file_by_name);
        newXS_deffile("Protobuf::DescriptorPool::_xs_find_message_by_name", XS_Protobuf__DescriptorPool__xs_find_message_by_name);
        newXS_deffile("Protobuf::DescriptorPool::_xs_find_enum_by_name", XS_Protobuf__DescriptorPool__xs_find_enum_by_name);
        newXS_deffile("Protobuf::DescriptorPool::_xs_find_extension_by_name", XS_Protobuf__DescriptorPool__xs_find_extension_by_name);
        newXS_deffile("Protobuf::Descriptor::File::_xs_name", XS_Protobuf__Descriptor__File__xs_name);
        newXS_deffile("Protobuf::Descriptor::File::_xs_package", XS_Protobuf__Descriptor__File__xs_package);
        newXS_deffile("Protobuf::Descriptor::File::_xs_top_level_message_count", XS_Protobuf__Descriptor__File__xs_top_level_message_count);
        newXS_deffile("Protobuf::Descriptor::File::_xs_top_level_message", XS_Protobuf__Descriptor__File__xs_top_level_message);
        newXS_deffile("Protobuf::Descriptor::MessageDef::_xs_full_name", XS_Protobuf__Descriptor__MessageDef__xs_full_name);
        newXS_deffile("Protobuf::Descriptor::MessageDef::_xs_name", XS_Protobuf__Descriptor__MessageDef__xs_name);
        newXS_deffile("Protobuf::Descriptor::MessageDef::_xs_field_count", XS_Protobuf__Descriptor__MessageDef__xs_field_count);
        newXS_deffile("Protobuf::Descriptor::MessageDef::_xs_field", XS_Protobuf__Descriptor__MessageDef__xs_field);
        newXS_deffile("Protobuf::Descriptor::MessageDef::_xs_find_field_by_name", XS_Protobuf__Descriptor__MessageDef__xs_find_field_by_name);
        newXS_deffile("Protobuf::Descriptor::MessageDef::_xs_find_field_by_number", XS_Protobuf__Descriptor__MessageDef__xs_find_field_by_number);
        newXS_deffile("Protobuf::Descriptor::Enum::_xs_full_name", XS_Protobuf__Descriptor__Enum__xs_full_name);
        newXS_deffile("Protobuf::Descriptor::Enum::_xs_name", XS_Protobuf__Descriptor__Enum__xs_name);
        newXS_deffile("Protobuf::Descriptor::Enum::_xs_value_count", XS_Protobuf__Descriptor__Enum__xs_value_count);
        newXS_deffile("Protobuf::Descriptor::Field::_xs_name", XS_Protobuf__Descriptor__Field__xs_name);
        newXS_deffile("Protobuf::Descriptor::Field::_xs_full_name", XS_Protobuf__Descriptor__Field__xs_full_name);
        newXS_deffile("Protobuf::Descriptor::Field::_xs_number", XS_Protobuf__Descriptor__Field__xs_number);
        newXS_deffile("Protobuf::Descriptor::Field::_xs_type", XS_Protobuf__Descriptor__Field__xs_type);
        newXS_deffile("Protobuf::Descriptor::Field::_xs_label", XS_Protobuf__Descriptor__Field__xs_label);
        newXS_deffile("Protobuf::Descriptor::Field::_xs_is_repeated", XS_Protobuf__Descriptor__Field__xs_is_repeated);
        newXS_deffile("Protobuf::Descriptor::Field::_xs_is_map", XS_Protobuf__Descriptor__Field__xs_is_map);
        newXS_deffile("Protobuf::Descriptor::Field::_xs_message_type", XS_Protobuf__Descriptor__Field__xs_message_type);
        newXS_deffile("Protobuf::Descriptor::Field::_xs_enum_type", XS_Protobuf__Descriptor__Field__xs_enum_type);
        newXS_deffile("Protobuf::Message::_xs_new_from_class", XS_Protobuf__Message__xs_new_from_class);
        newXS_deffile("Protobuf::Message::_xs_free", XS_Protobuf__Message__xs_free);
        newXS_deffile("Protobuf::Message::_xs_get", XS_Protobuf__Message__xs_get);
        newXS_deffile("Protobuf::Message::_xs_set", XS_Protobuf__Message__xs_set);
        newXS_deffile("Protobuf::Message::_xs_serialize", XS_Protobuf__Message__xs_serialize);
        newXS_deffile("Protobuf::Message::_xs_parse", XS_Protobuf__Message__xs_parse);
#if PERL_VERSION_LE(5, 21, 5)
#  if PERL_VERSION_GE(5, 9, 0)
    if (PL_unitcheckav)
        call_list(PL_scopestack_ix, PL_unitcheckav);
#  endif
    XSRETURN_YES;
#else
    Perl_xs_boot_epilog(aTHX_ ax);
#endif
}

#ifdef __cplusplus
}
#endif
